from fastapi import FastAPI
from contextlib import asynccontextmanager


from linkedin_rag.data.database import Base, engine

Base.metadata.create_all(bind=engine)

from linkedin_rag.utils.limiter import setup_limiter
from linkedin_rag.utils.scheduling import start_scheduler, stop_scheduler
from linkedin_rag.router.r_files import r_files
from linkedin_rag.router.r_postsearch import r_postsearch

@asynccontextmanager
async def lifespan(app: FastAPI):
    # Startup actions
    start_scheduler()
    
    yield
    # Shutdown actions
    stop_scheduler()
    

app = FastAPI(title="linkedin_rag", description="Generated by FastForge ⚡", version="0.1.0", lifespan=lifespan)

setup_limiter(app)

# from linkedin_rag.router import user
# app.include_router(user.router)

@app.get("/")
def root():
    return {"message": "Welcome to linkedin_rag"}
app.include_router(r_files)

app.include_router(r_postsearch)
