import click
from pathlib import Path
from jinja2 import Environment, FileSystemLoader

TEMPLATES_DIR = Path(__file__).parent.parent / "templates"

DB_URLS = {
    "sqlite": "sqlite:///./app.db",
    "postgresql": "postgresql://user:password@localhost/dbname",
    "mysql": "mysql+pymysql://user:password@localhost/dbname",
    "mongodb": "mongodb://localhost:27017/dbname",
}

COMMON_REQS = ["fastapi>=0.110.0","uvicorn[standard]>=0.29.0","pydantic>=2.0.0","pydantic-settings>=2.0.0","cryptography>=42.0.0","passlib[bcrypt]>=1.7.4","python-dotenv>=1.0.0","fastapi-cache2>=0.2.1","PyJWT>=2.8.0","slowapi>=0.1.9","apscheduler>=3.10.4","jinja2>=3.1.3","loguru>=0.7.2","python-multipart>=0.0.9"]
SQL_REQS = ["sqlalchemy>=2.0.0"]

REQUIREMENTS = {
    "sqlite": COMMON_REQS + SQL_REQS,
    "postgresql": COMMON_REQS + SQL_REQS + ["psycopg2-binary>=2.9.0"],
    "mysql": COMMON_REQS + SQL_REQS + ["pymysql>=1.1.0"],
    "mongodb": COMMON_REQS + ["motor>=3.3.0"],
}

def render(template_name, context):
    env = Environment(loader=FileSystemLoader(str(TEMPLATES_DIR / "project")))
    return env.get_template(template_name).render(**context)

def write(path, content):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    click.echo(f"  {'created':>10}  {path}")

def init_project(project_name, db):
    base = Path(project_name)
    if base.exists():
        click.echo(click.style(f"✗ '{project_name}' already exists.", fg="red"))
        raise SystemExit(1)

    click.echo(click.style(f"\n⚡ FastForge — initializing '{project_name}'\n", fg="cyan", bold=True))
    ctx = {"project_name": project_name, "db": db, "db_url": DB_URLS[db], "requirements": REQUIREMENTS[db]}

    pkg_name = project_name.lower()

    write(base / "app/main.py", render("main.py.j2", ctx))
    write(base / f"src/{pkg_name}/data/database.py", render("database.py.j2", ctx))
    write(base / f"src/{pkg_name}/config.py", render("config.py.j2", ctx))
    write(base / f"src/{pkg_name}/utils/crypto.py", render("crypto.py.j2", ctx))
    write(base / f"src/{pkg_name}/utils/connection_manager.py", render("connection_manager.py.j2", ctx))
    write(base / f"src/{pkg_name}/utils/limiter.py", render("limiter.py.j2", ctx))
    write(base / f"src/{pkg_name}/utils/scheduling.py", render("scheduling.py.j2", ctx))
    write(base / f"src/{pkg_name}/utils/crud_router.py", render("crud_router.py.j2", ctx))
    write(base / f"src/{pkg_name}/utils/controller.py", render("controller.py.j2", ctx))
    write(base / f"src/{pkg_name}/middleware/middleware.py", render("middleware.py.j2", ctx))
    write(base / f"src/{pkg_name}/data/actions.py", render("actions.py.j2", ctx))
    write(base / f"src/{pkg_name}/entity/base_entity.py", render("base_entity.py.j2", ctx))

    for pkg in [
        f"src/{pkg_name}",
        f"src/{pkg_name}/entity",
        f"src/{pkg_name}/schema",
        f"src/{pkg_name}/controller",
        f"src/{pkg_name}/service",
        f"src/{pkg_name}/router",
        f"src/{pkg_name}/data",
        f"src/{pkg_name}/utils",
        f"src/{pkg_name}/middleware",
        "app"
    ]:
        write(base / pkg / "__init__.py", "")

    write(base / "pyproject.toml", render("pyproject.toml.j2", ctx))
    write(base / "Makefile", render("Makefile.j2", ctx))
    write(base / ".env", f"DATABASE_URL={DB_URLS[db]}\nSECRET_KEY=change-me\nFERNET_KEY=\n")
    write(base / ".gitignore", "__pycache__/\n*.pyc\n.env\n*.db\n.venv/\n")
    write(base / "README.md", f"# {project_name}\n\nGenerated by **FastForge ⚡**\n\n## Setup & Run\n\n```bash\nmake install\nsource .venv/bin/activate\nmake run\n```\n")

    import os
    from fastforge.commands.make_entity import make_entity
    
    click.echo(click.style(f"\n⚡ Generating default Files entity...", fg="cyan"))
    original_dir = os.getcwd()
    os.chdir(base)
    try:
        make_entity("Files", ["filename:string", "content_type:string", "file_id:string"])
    except SystemExit:
        pass
    os.chdir(original_dir)

    click.echo(click.style(f"\n✔ Project '{project_name}' created!\n", fg="green", bold=True))
    click.echo(f"  cd {project_name}")
    click.echo(f"  make install")
    click.echo(f"  source .venv/bin/activate")
    click.echo(f"  fastforge make:entity User nom:string pwd:string:hash\n")
