name: 'analytics'
version: '1.0.0'
config-version: 2

profile: 'analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  analytics:
    # Applies to all files under models/
    +materialized: table
    +tags:
      - 'analytics'
    
    # Layer specific configs
    bronze:
      +materialized: view
      +tags: ['bronze']
    silver:
      +materialized: table
      +tags: ['silver']
    gold:
      +materialized: table
      +tags: ['gold']
